---
title: "Resample Test"
author: "Debbie Cannon"
date: "20/03/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r - load packages}


library(tidyverse)    # for general data science
library(tidymodels)   # for machine learning
library(corrplot)     # for visualising correlation matrices
library(vip)          # for variable importance plots
library(randomForest) # for the random forest model engine we will be using

```


## Load data

```{r prepare-data}
knee_data <- read_csv("Knee Replacement CCG 2021 (2).csv")

knee_data_filtered <- knee_data %>%
  select(`Pre-Op Q EQ5D Index`,`Age Band`,`Gender`,`Pre-Op Q EQ VAS`,`Knee Replacement Pre-Op Q Pain`:`Knee Replacement Pre-Op Q Score`,`Post-Op Q EQ5D Index`) %>%
  drop_na() %>%    # remove rows with missing values
  unique()    # keep unique rows


```


```{r data-splitting}

knee_split <- knee_data_filtered %>%
    initial_split(prop = 0.8,
                  strata = `Post-Op Q EQ5D Index`)

knee_train <- training(knee_split)
knee_test <- testing(knee_split)

```


```{r}

simple_rec <- knee_train %>%
  recipe(`Post-Op Q EQ5D Index` ~ `Pre-Op Q EQ5D Index`,`Pre-Op Q EQ VAS`,`Knee Replacement Pre-Op Q Pain`:`Knee Replacement Pre-Op Q Score`) %>%
  step_zv(all_predictors()) %>%
  step_corr(all_predictors())%>%
step_dummy(all_nominal_predictors())

```


## Model specification

Make sure you specify two different models:

```{r}

# Linear regression model specification: lm_spec
lm_spec <- linear_reg() 

# Random forest model specification: rf_spec
rf_spec <- rand_forest() %>%
    set_mode("regression") %>%
    set_engine("randomForest")

```

## Workflow

And two different workflows:

```{r specify-workflow}

# Linear model workflow: DZ_wflow_lm
knee_wflow_lm <-workflow() %>%
           add_recipe(simple_rec) %>%
           add_model(lm_spec)

# Random forest workflow: DZ_wflow_rf
knee_wflow_rf <-workflow() %>%
           add_recipe(simple_rec) %>%
           add_model(rf_spec)

```

```{r cross-validation}

knee_folds <- vfold_cv(knee_train, v = 10) # 10-fold cross validation

# We want to save the predictions
keep_pred <- control_resamples(save_pred = TRUE)

# Fit the two model:

# Linear regression (make sure you named the workflow DZ_wflow_lm)
knee_wflow_lm_fit <- knee_wflow_lm %>%
    fit_resamples(resamples = knee_folds, 
                  control = keep_pred)

# Random forest (make sure you named the workflow DZ_wflow_rf)
knee_wflow_rf_fit <- knee_wflow_rf %>%
    fit_resamples(resamples = knee_folds, 
                  control = keep_pred)
    
```


```{r cross-val-performance}

bind_rows(collect_metrics(knee_wflow_lm_fit) %>%
                          mutate(model = "linear_regression"),
          collect_metrics(knee_wflow_rf_fit) %>%
                          mutate(model = "random_forest"))

```

```{r cross-val-plot}

results <-  bind_rows(knee_wflow_lm_fit %>%
                          collect_predictions() %>%
                          mutate(model = "linear_regression") %>%
                          rename(pred_PostEQ5D = .pred),
                      knee_wflow_rf_fit %>%
                          collect_predictions() %>%
                          mutate(model = "random_forest") %>%
                          rename(pred_PostEQ5D = .pred))

results %>%
    ggplot(aes(x = `Post-Op Q EQ5D Index`, y = pred_PostEQ5D)) +
    geom_abline(intercept=0, slope=1) +  # we want data to fall close to this line
    geom_point() +
    facet_wrap(~ model)

```

```{r final-fit}

# Fit the two models (make sure you named the data split object DZ_split)

knee_wflow_lm_finalfit <- knee_wflow_lm %>%
    last_fit(knee_split)

knee_wflow_rf_finalfit <- knee_wflow_rf %>%
    last_fit(knee_split)

# Print performance metrics on testing data
bind_rows(collect_metrics(knee_wflow_lm_finalfit) %>%
                          mutate(model = "linear_regression"),
          collect_metrics(knee_wflow_rf_finalfit) %>%
                          mutate(model = "random_forest"))

```


